version: '3'
services:
  react-ui:
    build:
      context: ./client
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    container_name: server